'use client'

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React, { useState } from 'react';
import "./globals.css";
import Header from '@/components/Header'
import { ThemeContext } from "@/context/themeContext";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Job Chaser",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkTheme, setTheme] = useState(false);

  function toggleTheme():void {
      setTheme(prevTheme =>  !prevTheme);
  }

  const themeStyles = {
    backgroundColor: darkTheme ? '#333' : '#fff',
    color: darkTheme ? '#fff' : '#333',
    paddingBottom: '13rem', /* Get darkTheme for the main margin (13rem) too */
  };

  return (
    <>
    <head>
      <meta name="description" content="Job Chaser application" />
      <title>Job Chaser</title>
    </head>
    <html lang="en">
      <ThemeContext.Provider value={{darkTheme, toggleTheme}}>
          <StoreProvider>
          <body
            style={themeStyles}
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Header/>
            {children}
          </body>
          </StoreProvider>
      </ThemeContext.Provider>
    </html>
    </>
  );
}
